### ISSUE TITLE
extracting all attributes

### ISSUE THREAD

**Issue by khia** [msoap/html2data#1]
I am trying to extract tiddlers from tiddlywiki. They are represented as
```
<div created="20171224152829428" modified="20171224152917440" tags="" title="foobaz">
<pre>bar</pre>
</div>
```
I can get list of tiddlers using:
```
html2data ~/Downloads/empty.html 'div[created]:attr(title)'
```
I can get the content of every tiddler using:
```
html2data ~/Downloads/empty.html 'div[title="foobar"]:html'
```
I can extract single attribute from tiddler:
```
html2data ~/Downloads/empty.html 'div[title="foobar"]:attr(tags)'
```

But I couldn't figure out how to extract all attributes of the div. Ideally I would like to be able to extract entire div as is.

**Comment by msoap** [comment]
This can only be done by specifying all the attributes explicitly:
```
html2data ~/Downloads/empty.html :created 'div[title="foobaz"]:attr(created)' :modified 'div[title="foobaz"]:attr(modified)' :title 'div[title="foobaz"]:attr(title)'
```

output:
```
created:	20171224152829428
modified:	20171224152917440
title:	foobaz
```

Or specify parent `div` (for extract entire div as is):
```
html2data ~/Downloads/empty.html 'div_parent:html'
```

**Comment by khia** [comment]
thank you for the explanation
